
      // 
      // Javascript generated by HTML2 Toolkit plugin
      // 
      var tree;
      
      function treeInit() {
      tree = new YAHOO.widget.TreeView("treeDiv1");
      var root = tree.getRoot();

      
var objd62e81 = {
  label: " DITA For Small Teams",
  href: "topics/dita-for-small-teams.html", 
  target:"contentwin"
};
var d62e81 = new YAHOO.widget.TextNode(objd62e81, root, false);

var objd62e106 = {
  label: " DITA for Small Teams Tools",
  href: "topics/dfst-tools.html", 
  target:"contentwin"
};
var d62e106 = new YAHOO.widget.TextNode(objd62e106, d62e81, false);

var objd62e131 = {
  label: " git: Distributed and Shared Access to Content",
  href: "topics/tools-git.html", 
  target:"contentwin"
};
var d62e131 = new YAHOO.widget.TextNode(objd62e131, d62e106, false);

var objd62e156 = {
  label: " eXist-db: Enabling Search and Link Management",
  href: "topics/tools-exist-db.html", 
  target:"contentwin"
};
var d62e156 = new YAHOO.widget.TextNode(objd62e156, d62e106, false);
var d73e3 = new YAHOO.widget.TextNode("Index", root, false);

      
      tree.draw(); 
      } 
      
      YAHOO.util.Event.addListener(window, "load", treeInit);       
    